"""
Find the MeteoSwiss forecast point for a location name or a Swiss postal code.

The points are the 5,614 places MeteoSwiss publishes local forecasts for: postal code areas, weather
stations and points of interest.
"""
import csv
import logging
import unicodedata
from datetime import datetime, timedelta, timezone
from importlib import resources
from pathlib import Path
from typing import Dict, List, NamedTuple, Tuple

from .errors import CannotAnswerError
from .opendata import download_file

logger = logging.getLogger(__name__)

POINT_TABLE_URL = "https://data.geo.admin.ch/ch.meteoschweiz.ogd-local-forecasting/ogd-local-forecasting_meta_point.csv"
# Names of places in other languages, mapped to the MeteoSwiss point name; generated by
# scripts/build_other_language_place_names.py from Wikipedia lists
OTHER_LANGUAGE_PLACE_NAMES_FILE = "other_language_place_names.csv"

POINT_TABLE_MAX_AGE = timedelta(days=7)


class ForecastPoint(NamedTuple):
    """A forecast location as the MeteoSwiss point table describes it."""
    point_id: str
    point_type_id: str
    name: str
    postal_code: str
    altitude_m: float
    east_m: float   # LV95, the Swiss grid in metres
    north_m: float  # LV95

    @property
    def display_name(self) -> str:
        """The name shown to a reader, with postal code and altitude, such as "Zermatt 3920 (1610 m)"."""
        name_with_code = f"{self.name} {self.postal_code}" if self.postal_code else self.name
        return f"{name_with_code} ({self.altitude_m:.0f} m)"

    @property
    def row_prefix(self) -> bytes:
        """The start every data row of this point has, such as b"800100;2;"."""
        return f"{self.point_id};{self.point_type_id};".encode()


def _rank_point(point: ForecastPoint) -> Tuple[bool, str, int]:
    """
    Sort key that picks one point when several share a name, so a name always gives the same
    point: postal code points before stations and points of interest, then the lowest postal
    code, then the lowest point id. It is a fixed order, not a judgement of which point fits best.
    """
    return (not point.postal_code, point.postal_code, int(point.point_id))


def _normalise_location(location: str) -> str:
    """
    Fold case and strip accents so "zurich" finds "Zürich".

    Parameters:
        location (str): A location name or postal code.

    Returns:
        str: Comparable form of the location.
    """
    folded = unicodedata.normalize("NFKD", location.casefold())
    without_accents = "".join(character for character in folded if not unicodedata.combining(character))
    return without_accents.strip()


def _read_other_language_place_name_rows() -> List[Dict[str, str]]:
    """Read the rows of the other language place names file, without its comment lines."""
    text = resources.files("swiss_weather_mcp").joinpath(OTHER_LANGUAGE_PLACE_NAMES_FILE).read_text(encoding="utf-8")
    lines = [line for line in text.splitlines() if not line.startswith("#")]
    return list(csv.DictReader(lines, delimiter=";"))


def _load_other_language_place_names() -> Dict[str, str]:
    """Map each other language place name, normalised, to its normalised MeteoSwiss point name."""
    point_names_by_other_language_place_name = {}
    for row in _read_other_language_place_name_rows():
        other_language_place_name = _normalise_location(row["other_language_place_name"])
        point_names_by_other_language_place_name[other_language_place_name] = _normalise_location(row["meteoswiss_point_name"])
    return point_names_by_other_language_place_name


class LocationFinder:
    """Find forecast points by name or postal code in the MeteoSwiss point table, cached on disk."""

    def __init__(self, cache_dir: Path):
        self.cache_dir = cache_dir / "locations"
        self._points: List[ForecastPoint] = []
        self._point_names_by_other_language_place_name = _load_other_language_place_names()

    def _ensure_point_table(self) -> Path:
        """Return the cached point table, downloading it when it is missing or stale."""
        point_table = self.cache_dir / "ogd-local-forecasting_meta_point.csv"
        if point_table.exists():
            modified_at = datetime.fromtimestamp(point_table.stat().st_mtime, timezone.utc)
            age = datetime.now(timezone.utc) - modified_at
            if age < POINT_TABLE_MAX_AGE:
                return point_table

        logger.info("Downloading the MeteoSwiss forecast point table")
        download_file(POINT_TABLE_URL, point_table)
        return point_table

    def _load_points(self) -> List[ForecastPoint]:
        """Read the point table into memory once per process."""
        if self._points:
            return self._points

        point_table = self._ensure_point_table()
        points: List[ForecastPoint] = []
        with open(point_table, newline="", encoding="latin-1") as file:
            for row in csv.DictReader(file, delimiter=";"):
                points.append(ForecastPoint(
                    point_id=row["point_id"],
                    point_type_id=row["point_type_id"],
                    name=row["point_name"],
                    postal_code=row["postal_code"],
                    altitude_m=float(row["point_height_masl"]),
                    east_m=float(row["point_coordinates_lv95_east"]),
                    north_m=float(row["point_coordinates_lv95_north"]),
                ))
        # Published only once complete, so a parallel request never sees part of the table
        self._points = points
        logger.info(f"Loaded {len(points)} forecast locations")
        return points

    def find_point(self, location: str) -> ForecastPoint:
        """
        Find the forecast point for a location name or a Swiss postal code.

        Case and accents are ignored, and names in other languages such as "Genf" are read as the
        name MeteoSwiss uses; otherwise only exact matches count. When several points match, the
        one with the lowest postal code is used, and a weather station otherwise.

        Parameters:
            location (str): Location name (e.g., "Zurich") or postal code (e.g., "8001").

        Returns:
            ForecastPoint: The resolved forecast point.
        """
        points = self._load_points()
        normalised_location = _normalise_location(location)
        normalised_location = self._point_names_by_other_language_place_name.get(normalised_location, normalised_location)

        matches = [point for point in points if point.postal_code == normalised_location]
        if not matches:
            matches = [point for point in points if _normalise_location(point.name) == normalised_location]
        if not matches:
            raise CannotAnswerError(
                f"Location '{location}' is not one of the {len(points)} places MeteoSwiss publishes "
                f"forecasts for. Check the spelling, or try a nearby town, village or postal code."
            )

        return min(matches, key=_rank_point)
