import csv
import logging
from importlib import resources
import shutil
import threading
import unicodedata
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional, Tuple

import requests

from . import parameters
from .opendata import REQUEST_TIMEOUT_SECONDS, download_file, parse_stamp

logger = logging.getLogger(__name__)

COLLECTION_ID = "ch.meteoschweiz.ogd-local-forecasting"
STAC_BASE_URL = "https://data.geo.admin.ch/api/stac/v1"
POINT_TABLE_URL = f"https://data.geo.admin.ch/{COLLECTION_ID}/ogd-local-forecasting_meta_point.csv"
# Names of places in other languages, mapped to the MeteoSwiss point name; generated by
# scripts/build_other_language_place_names.py from Wikipedia lists
OTHER_LANGUAGE_PLACE_NAMES_FILE = "other_language_place_names.csv"

POINT_TABLE_MAX_AGE = timedelta(days=7)
RUN_LOOKUP_MAX_AGE = timedelta(minutes=5)


class ForecastPoint(NamedTuple):
    """A forecast location as the MeteoSwiss point table describes it."""
    point_id: str
    point_type_id: str
    name: str
    postal_code: str
    altitude_m: float

    @property
    def display_name(self) -> str:
        """The name shown to a reader, with postal code and altitude, such as "Zermatt 3920 (1610 m)"."""
        name_with_code = f"{self.name} {self.postal_code}" if self.postal_code else self.name
        return f"{name_with_code} ({self.altitude_m:.0f} m)"

    @property
    def row_prefix(self) -> bytes:
        """The start every data row of this point has, such as b"800100;2;"."""
        return f"{self.point_id};{self.point_type_id};".encode()


class ForecastSeries(NamedTuple):
    """One parameter over the whole forecast window at one point, with the run it came from."""
    run_time: datetime
    values: Dict[datetime, float]


def _rank_point(point: ForecastPoint) -> Tuple[bool, str, int]:
    """
    Sort key that picks one point when several share a name, so a name always gives the same
    point: postal code points before stations and points of interest, then the lowest postal
    code, then the lowest point id. It is a fixed order, not a judgement of which point fits best.
    """
    return (not point.postal_code, point.postal_code, int(point.point_id))


def _normalise_location(location: str) -> str:
    """
    Fold case and strip accents so "zurich" finds "Zürich".

    Parameters:
        location (str): A location name or postal code.

    Returns:
        str: Comparable form of the location.
    """
    folded = unicodedata.normalize("NFKD", location.casefold())
    without_accents = "".join(character for character in folded if not unicodedata.combining(character))
    return without_accents.strip()


def _read_other_language_place_name_rows() -> List[Dict[str, str]]:
    """Read the rows of the other language place names file, without its comment lines."""
    text = resources.files("swiss_weather_mcp").joinpath(OTHER_LANGUAGE_PLACE_NAMES_FILE).read_text(encoding="utf-8")
    lines = [line for line in text.splitlines() if not line.startswith("#")]
    return list(csv.DictReader(lines, delimiter=";"))


def _load_other_language_place_names() -> Dict[str, str]:
    """Map each other language place name, normalised, to its normalised MeteoSwiss point name."""
    point_names_by_other_language_place_name = {}
    for row in _read_other_language_place_name_rows():
        other_language_place_name = _normalise_location(row["other_language_place_name"])
        point_names_by_other_language_place_name[other_language_place_name] = _normalise_location(row["meteoswiss_point_name"])
    return point_names_by_other_language_place_name


class LocalForecastSource:
    """Read point forecasts from the MeteoSwiss local forecasting collection, cached per model run."""

    def __init__(self, cache_dir: Path, cache_all_locations: bool = False):
        self.cache_dir = cache_dir
        self.cache_all_locations = cache_all_locations
        self._points: List[ForecastPoint] = []
        self._point_names_by_other_language_place_name = _load_other_language_place_names()
        self._run_id: Optional[str] = None
        self._run_file_urls: Dict[str, str] = {}
        self._run_checked_at: Optional[datetime] = None
        # A tool reads its files in parallel, and all of them must come from the same run
        self._run_lookup_lock = threading.Lock()

    def _ensure_point_table(self) -> Path:
        """Return the cached point table, downloading it when it is missing or stale."""
        point_table = self.cache_dir / "ogd-local-forecasting_meta_point.csv"
        if point_table.exists():
            modified_at = datetime.fromtimestamp(point_table.stat().st_mtime, timezone.utc)
            age = datetime.now(timezone.utc) - modified_at
            if age < POINT_TABLE_MAX_AGE:
                return point_table

        logger.info("Downloading the MeteoSwiss forecast point table")
        download_file(POINT_TABLE_URL, point_table)
        return point_table

    def _load_points(self) -> List[ForecastPoint]:
        """Read the point table into memory once per process."""
        if self._points:
            return self._points

        point_table = self._ensure_point_table()
        points: List[ForecastPoint] = []
        with open(point_table, newline="", encoding="latin-1") as file:
            for row in csv.DictReader(file, delimiter=";"):
                points.append(ForecastPoint(
                    point_id=row["point_id"],
                    point_type_id=row["point_type_id"],
                    name=row["point_name"],
                    postal_code=row["postal_code"],
                    altitude_m=float(row["point_height_masl"]),
                ))
        # Published only once complete, so a parallel request never sees part of the table
        self._points = points
        logger.info(f"Loaded {len(points)} forecast locations")
        return points

    def find_point(self, location: str) -> ForecastPoint:
        """
        Find the forecast point for a location name or a Swiss postal code.

        Case and accents are ignored, and names in other languages such as "Genf" are read as the
        name MeteoSwiss uses; otherwise only exact matches count. When several points match, the
        one with the lowest postal code is used, and a weather station otherwise.

        Parameters:
            location (str): Location name (e.g., "Zurich") or postal code (e.g., "8001").

        Returns:
            ForecastPoint: The resolved forecast point.
        """
        points = self._load_points()
        normalised_location = _normalise_location(location)
        normalised_location = self._point_names_by_other_language_place_name.get(normalised_location, normalised_location)

        matches = [point for point in points if point.postal_code == normalised_location]
        if not matches:
            matches = [point for point in points if _normalise_location(point.name) == normalised_location]
        if not matches:
            raise ValueError(
                f"Location '{location}' is not one of the {len(points)} places MeteoSwiss publishes "
                f"forecasts for. Check the spelling, or try a nearby town, village or postal code."
            )

        return min(matches, key=_rank_point)

    def _fetch_file_urls_by_run(self, day: date) -> Dict[str, Dict[str, str]]:
        """Return the file URLs of one daily STAC item, grouped by run and keyed by parameter."""
        item_url = f"{STAC_BASE_URL}/collections/{COLLECTION_ID}/items/{day.strftime('%Y%m%d')}-ch"
        response = requests.get(item_url, timeout=REQUEST_TIMEOUT_SECONDS)
        if response.status_code == 404:
            return {}
        response.raise_for_status()

        file_urls_by_run: Dict[str, Dict[str, str]] = {}
        for asset_name, asset in response.json().get("assets", {}).items():
            # Asset names look like vnut12.lssw.<run>.<parameter>.csv
            name_parts = asset_name.split(".")
            if len(name_parts) != 5:
                continue
            _, _, run_id, parameter, _ = name_parts
            file_urls_by_run.setdefault(run_id, {})[parameter] = asset["href"]
        return file_urls_by_run

    def find_latest_run(self) -> Tuple[str, Dict[str, str]]:
        """
        Find the newest published run and the parameter files it holds, reusing the answer for
        RUN_LOOKUP_MAX_AGE.

        Returns:
            Tuple[str, Dict[str, str]]: The run ID (YYYYMMDDHHMM, UTC) and its parameter file URLs.
        """
        with self._run_lookup_lock:
            now = datetime.now(timezone.utc)
            if self._run_id is not None and self._run_checked_at and now - self._run_checked_at < RUN_LOOKUP_MAX_AGE:
                return self._run_id, self._run_file_urls

            # Items are named by UTC day. MeteoSwiss uploads the files of a run one by one over a few
            # minutes, so the newest run can be incomplete. Just after 00:00 UTC, the newest complete
            # run is then in yesterday's item.
            today = now.date()
            for day in (today, today - timedelta(days=1)):
                file_urls_by_run = self._fetch_file_urls_by_run(day)
                complete_run_ids = []
                for run_id, file_urls in file_urls_by_run.items():
                    if parameters.ALL_PARAMETERS.issubset(file_urls):
                        complete_run_ids.append(run_id)
                if complete_run_ids:
                    # Run IDs are fixed width, so the newest run is the largest string
                    self._run_id = max(complete_run_ids)
                    self._run_file_urls = file_urls_by_run[self._run_id]
                    self._run_checked_at = now
                    return self._run_id, self._run_file_urls

        raise RuntimeError(
            "The MeteoSwiss local forecasting collection published no complete run for today or yesterday"
        )

    def _drop_superseded_runs(self, current_run_id: str) -> None:
        """Remove the folders of runs older than the current one, except the run just before it."""
        # Run IDs are fixed width, so comparing them as text compares them in time
        older_runs = []
        for folder in (self.cache_dir / "runs").iterdir():
            if folder.is_dir() and folder.name < current_run_id:
                older_runs.append(folder)

        older_runs.sort()

        # Keep the previous run. Another request, or another server using the same cache, may
        # still read from it for a few minutes. Runs come an hour apart, so one is enough.
        for folder in older_runs[:-1]:
            logger.info(f"Dropping superseded run {folder.name}")
            shutil.rmtree(folder, ignore_errors=True)

    def _ensure_parameter_file(self, parameter: str, point: ForecastPoint, run_id: str, file_url: str) -> Path:
        """Return the cached file with this parameter for this point and run, downloading it if missing."""
        run_dir = self.cache_dir / "runs" / run_id
        full_file = run_dir / f"{parameter}.csv"
        point_file = run_dir / f"{parameter}_{point.point_id}_{point.point_type_id}.csv"

        # A full file from an earlier download serves every point
        if full_file.exists():
            return full_file
        if point_file.exists():
            return point_file

        logger.info(f"Reading {parameter} for {point.display_name} from run {run_id}")
        if self.cache_all_locations:
            download_file(file_url, full_file)
            downloaded_file = full_file
        else:
            download_file(file_url, point_file, only_rows_starting_with=point.row_prefix)
            downloaded_file = point_file

        self._drop_superseded_runs(run_id)
        return downloaded_file

    def _read_point_values(self, parameter_file: Path, point: ForecastPoint) -> Dict[datetime, float]:
        """Read one point's values from a cached file, keyed by UTC timestamp."""
        row_prefix = point.row_prefix
        values: Dict[datetime, float] = {}

        with open(parameter_file, "rb") as file:
            for line in file:
                # This also skips the header of a full file, a point extract has none
                if not line.startswith(row_prefix):
                    continue
                _, _, stamp_text, value_text = line.decode("latin-1").strip().split(";")
                try:
                    stamp = parse_stamp(stamp_text)
                    values[stamp] = float(value_text)
                except ValueError:
                    continue  # gaps are published as empty fields

        return values

    def read_series(self, parameter: str, point: ForecastPoint) -> ForecastSeries:
        """
        Read one parameter over the whole forecast window at one point.

        Parameters:
            parameter (str): MeteoSwiss parameter shortname (e.g., "tre200h0", "fu3010h0").
            point (ForecastPoint): The resolved forecast point.

        Returns:
            ForecastSeries: The run the values came from, and the values keyed by UTC timestamp.
        """
        run_id, file_urls = self.find_latest_run()
        if parameter not in file_urls:
            raise ValueError(f"MeteoSwiss's newest forecast does not include '{parameter}'.")

        parameter_file = self._ensure_parameter_file(parameter, point, run_id, file_urls[parameter])
        values = self._read_point_values(parameter_file, point)
        if not values:
            raise ValueError(
                f"MeteoSwiss publishes no '{parameter}' values for {point.display_name}. Some entries, "
                f"such as the regional ones, only carry part of the forecast, try a nearby town."
            )

        return ForecastSeries(run_time=parse_stamp(run_id), values=values)
